### Verbo GET – listar todos
GET http://localhost:8000/cliente/ HTTP/1.1

### Verbo GET – listar um
GET http://localhost:8000/cliente/{id} HTTP/1.1

### Verbo POST – adicionar
POST http://127.0.0.1:8000/cliente/ HTTP/1.1
content-type: application/json

{
    "nome": "Tio Sr Lucioando",
    "cpf": "191202834876",
    "telefone": "49929999999"
}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/cliente/1 HTTP/1.1
content-type: application/json

{
    "nome": "Pablo Valente Neto",
    "telefone": "49988884457"
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/cliente/2 HTTP/1.1

#PABLO VALENTE NETO - 2026.1 - UNIPLAC - DESENVOLVIMENTO WEB - AULA 03-20
