### Login para obter access e refresh tokens
POST http://127.0.0.1:8000/auth/login HTTP/1.1
content-type: application/json

{
"cpf" : "1",
"senha" : "abcBolinhas"
}

### token gerado

@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaWQiOjIsImdydXBvIjoyLCJleHAiOjE3NzQ4MTUxMDgsInR5cGUiOiJhY2Nlc3MifQ.Qs9Un1cLQN3-tS30QM7m3O_KUci9y9ZvDCclUG1g2cQ

@refresh_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaWQiOjIsImdydXBvIjoyLCJleHAiOjE3NzU0MTkxMjMsInR5cGUiOiJyZWZyZXNoIn0.WwzqzrC_5XhCJeFn3qA0He8fH_qYg6_os5Y5bc_6Ci8

### testar access token para acessar endpoint protegido
GET http://127.0.0.1:8000/auth/me HTTP/1.1
Authorization: Bearer {{access_token}}

### Usar refresh token para obter novos tokens


POST http://localhost:8000/auth/refresh
Content-Type: application/json
{
"refresh_token": "{{refresh_token}}"
}