### Verbo GET – listar todos
GET http://localhost:8000/funcionario/ HTTP/1.1

### Verbo GET – listar um
GET http://localhost:8000/funcionario/{id} HTTP/1.1

### Verbo POST – adicionar
POST http://127.0.0.1:8000/funcionario/ HTTP/1.1
content-type: application/json

{
    "nome": "Zé Mestre das Informaticas da Silva",
    "matricula": "Ze9182",
    "cpf": "928310928374",
    "telefone": "49999901109",
    "grupo": 1,
    "senha": "Deteuspulospontocom"
}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/funcionario/1 HTTP/1.1
content-type: application/json

{
    "telefone": "49988512347",
    "grupo": 4
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/funcionario/2 HTTP/1.1

#PABLO VALENTE NETO - 2026.1 - UNIPLAC - DESENVOLVIMENTO WEB - AULA 03-20
