### Verbo GET – listar todos
GET http://localhost:8000/cliente/ HTTP/1.1

### Verbo GET – listar um
GET http://localhost:8000/cliente/2 HTTP/1.1

### Verbo POST – adicionar
POST http://127.0.0.1:8000/cliente/ HTTP/1.1
content-type: application/json

{
    "nome": "Pablo Valente Neto",
    "cpf": "012927312438",
    "telefone": "49921512399"
}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/cliente/1 HTTP/1.1
content-type: application/json

{
    "nome": "Pablo Valente Neto",
    "telefone": "49988123457"
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/cliente/1 HTTP/1.1

#PABLO VALENTE NETO - 2026.1 - UNIPLAC - DESENVOLVIMENTO WEB - AULA 03-20
